In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
df2024 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2024\2024Sepsis00110.csv', encoding='big5')
df2025 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2025\2025Sepsis00110.csv', encoding='big5')

table10 = pd.concat([df2024, df2025], ignore_index=True)

In [4]:
table10 = table10.dropna(how='all')
table10 = table10[table10['ACCOUNTNO'].notna()]
table10 = table10.loc[:, ~table10.columns.str.contains('^Unnamed')]

In [5]:
table10

,DIVISIONNO,ACCOUNTNO,IPDACCOUNTNO,DM,CARDIOVASCULAR,RESPIRATORY,CNS,CANCER,LIVER,KIDNEY,AUTOIMMUNE,DISEASECNT
0,001,I11300000001,NaN,N,N,N,N,N,N,N,N,0.0
1,001,I11300000002,I11300000176,N,Y,Y,Y,N,Y,Y,Y,6.0
2,001,I11300000003,NaN,N,N,N,N,N,N,N,N,0.0
3,001,I11300000004,NaN,N,N,N,N,N,N,N,N,0.0
4,001,I11300000005,NaN,N,N,N,N,N,N,N,N,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
88934,001,I11400060735,NaN,N,N,N,N,N,N,N,N,0.0
88935,001,I11400060736,NaN,N,Y,Y,Y,Y,Y,Y,Y,7.0
88936,001,I11400060737,NaN,N,N,N,N,N,N,N,N,0.0
88937,001,I11400060738,NaN,N,Y,N,Y,N,Y,Y,Y,5.0
88938,001,I11400060739,NaN,N,N,Y,N,N,N,N,N,1.0

In [6]:
len(table10),len(table10['ACCOUNTNO'].unique())

(88938, 88938)

In [7]:
table10.columns

Index(['DIVISIONNO', 'ACCOUNTNO', 'IPDACCOUNTNO', 'DM', 'CARDIOVASCULAR',
       'RESPIRATORY', 'CNS', 'CANCER', 'LIVER', 'KIDNEY', 'AUTOIMMUNE',
       'DISEASECNT'],
      dtype='object')

In [8]:
table10_clear = table10[['ACCOUNTNO','DM','CARDIOVASCULAR', 'RESPIRATORY', 'CNS',
       'CANCER', 'LIVER','KIDNEY','AUTOIMMUNE']]

In [9]:
table10_clear

,ACCOUNTNO,DM,CARDIOVASCULAR,RESPIRATORY,CNS,CANCER,LIVER,KIDNEY,AUTOIMMUNE
0,I11300000001,N,N,N,N,N,N,N,N
1,I11300000002,N,Y,Y,Y,N,Y,Y,Y
2,I11300000003,N,N,N,N,N,N,N,N
3,I11300000004,N,N,N,N,N,N,N,N
4,I11300000005,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...
88934,I11400060735,N,N,N,N,N,N,N,N
88935,I11400060736,N,Y,Y,Y,Y,Y,Y,Y
88936,I11400060737,N,N,N,N,N,N,N,N
88937,I11400060738,N,Y,N,Y,N,Y,Y,Y
88938,I11400060739,N,N,Y,N,N,N,N,N

In [10]:
table10_clear.to_csv('table10_clear.csv', index=False)