In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df2024 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2024\2024Sepsis00102.csv', encoding='big5', dtype={0: str, 12: str})
df2025 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2025\2025Sepsis00102.csv', encoding='big5', dtype={0: str, 12: str})

table2 = pd.concat([df2024, df2025], ignore_index=True)

In [3]:
table2 = table2.dropna(how='all')
table2 = table2[table2['ACCOUNTNO'].notna()]
table2 = table2.loc[:, ~table2.columns.str.contains('^Unnamed')]

In [4]:
table2

,DIVISIONNO,ACCOUNTNO,IPDACCOUNTNO,ISSEPSIS0,ISSEPSIS1,ISSEPSIS3,VITALSIGNSBT,VITALSIGNSPR,VITALSIGNSRR,VITALSIGNSSPO2,...,HEARTC,ARRIVALWAYNO,ISTRANSFER,ISTRAVELCASE,ISCLUSTER,IPDCOUNT,MAP,INJURELEVEL,ISTRAUMA,ISCANCELSEPSIS
0,001,I11300000001,NaN,N,N,N,36.0,74.0,18.0,NaN,...,N,A,N,N,N,0.0,98.0,3.0,Y,N
1,001,I11300000002,I11300000176,N,N,N,38.2,106.0,20.0,95.0,...,N,A,N,N,N,0.0,113.0,3.0,N,N
2,001,I11300000003,NaN,N,N,N,36.4,88.0,20.0,NaN,...,N,A,N,N,N,0.0,105.0,4.0,N,N
3,001,I11300000004,NaN,N,N,N,36.0,90.0,18.0,NaN,...,N,E,N,N,N,0.0,80.0,3.0,N,N
4,001,I11300000005,NaN,N,N,N,36.0,87.0,18.0,NaN,...,N,A,N,N,N,0.0,91.0,3.0,Y,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88934,001,I11400060735,NaN,N,N,N,36.9,117.0,20.0,99.0,...,N,A,N,N,N,0.0,104.0,3.0,Y,N
88935,001,I11400060736,NaN,N,N,N,36.6,78.0,20.0,95.0,...,N,A,N,N,N,0.0,100.0,3.0,N,N
88936,001,I11400060737,NaN,N,N,N,37.1,84.0,20.0,100.0,...,N,A,N,N,N,0.0,88.0,2.0,N,N
88937,001,I11400060738,NaN,N,N,N,36.3,79.0,20.0,96.0,...,N,A,N,N,N,0.0,116.0,3.0,N,N
88938,001,I11400060739,NaN,N,N,N,36.7,103.0,18.0,97.0,...,N,A,N,N,N,0.0,86.0,2.0,N,N

In [5]:
len(table2),len(table2['ACCOUNTNO'].unique())

(88938, 88938)

In [6]:
table2.columns

Index(['DIVISIONNO', 'ACCOUNTNO', 'IPDACCOUNTNO', 'ISSEPSIS0', 'ISSEPSIS1',
       'ISSEPSIS3', 'VITALSIGNSBT', 'VITALSIGNSPR', 'VITALSIGNSRR',
       'VITALSIGNSSPO2', 'VITALSIGNSSBP', 'VITALSIGNSDBP', 'CONSCIOUSNESSE',
       'CONSCIOUSNESSM', 'CONSCIOUSNESSV', 'VITALSIGNSGCS', 'ISACUTECHANGE',
       'CONSCIOUSNESSA', 'CONSCIOUSNESSB', 'CONSCIOUSNESSC', 'FEVER',
       'FEVERCOUGH', 'FEVERHEADACHE', 'FEVERMUSCLEPAIN', 'FEVERABDOMINALPAIN',
       'FEVERDIARRHEA', 'FEVERDYSPNEA', 'RESPIRATORYTRACTA',
       'RESPIRATORYTRACTB', 'RESPIRATORYTRACTC', 'RESPIRATORYTRACTD',
       'RESPIRATORYTRACTE', 'RESPIRATORY', 'CIRCULATION', 'HEARTA', 'HEARTB',
       'HEARTC', 'ARRIVALWAYNO', 'ISTRANSFER', 'ISTRAVELCASE', 'ISCLUSTER',
       'IPDCOUNT', 'MAP', 'INJURELEVEL', 'ISTRAUMA', 'ISCANCELSEPSIS'],
      dtype='object')

In [7]:
table2_clear = table2[['ACCOUNTNO','ISSEPSIS0','VITALSIGNSBT', 'VITALSIGNSPR', 'VITALSIGNSRR',
       'VITALSIGNSSPO2', 'VITALSIGNSDBP', 'VITALSIGNSGCS','MAP','FEVER','INJURELEVEL']]

In [8]:
table2_clear

,ACCOUNTNO,ISSEPSIS0,VITALSIGNSBT,VITALSIGNSPR,VITALSIGNSRR,VITALSIGNSSPO2,VITALSIGNSDBP,VITALSIGNSGCS,MAP,FEVER,INJURELEVEL
0,I11300000001,N,36.0,74.0,18.0,NaN,84.0,15.0,98.0,Y,3.0
1,I11300000002,N,38.2,106.0,20.0,95.0,93.0,15.0,113.0,Y,3.0
2,I11300000003,N,36.4,88.0,20.0,NaN,85.0,15.0,105.0,Y,4.0
3,I11300000004,N,36.0,90.0,18.0,NaN,68.0,15.0,80.0,Y,3.0
4,I11300000005,N,36.0,87.0,18.0,NaN,74.0,15.0,91.0,Y,3.0
...,...,...,...,...,...,...,...,...,...,...,...
88934,I11400060735,N,36.9,117.0,20.0,99.0,84.0,15.0,104.0,Y,3.0
88935,I11400060736,N,36.6,78.0,20.0,95.0,77.0,15.0,100.0,Y,3.0
88936,I11400060737,N,37.1,84.0,20.0,100.0,77.0,15.0,88.0,Y,2.0
88937,I11400060738,N,36.3,79.0,20.0,96.0,89.0,15.0,116.0,Y,3.0
88938,I11400060739,N,36.7,103.0,18.0,97.0,73.0,15.0,86.0,Y,2.0

In [9]:
table2_clear.to_csv('table2_clear.csv', index=False)