In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df2024 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2024\2024Sepsis00105.csv', encoding='big5')
df2025 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2025\2025Sepsis00105.csv', encoding='big5')

table5 = pd.concat([df2024, df2025], ignore_index=True)

In [4]:
table5 = table5.dropna(how='all')
# table5 = table5[table5['ACCOUNTNO'].notna()]
table5 = table5.loc[:, ~table5.columns.str.contains('^Unnamed')]

2024: 4468
2025: 3511

In [4]:
table5

,DIVISIONNO,ACCOUNTNO,IPDACCOUNTNO,ISCHECK27,CHECKITEM27,CHECKITEM27SCORE,ISCHECK28,CHECKITEM28FACTOR2,CHECKITEM28A,CHECKITEM28B,...,CHECKITEM30FACTOR2,CHECKITEM30,CHECKITEM30SCORE,ISCHECK31,CHECKITEM31,CHECKITEM31SCORE,ISCHECK32,CHECKITEM32,CHECKITEM32SCORE,SOFASCORE
0,001,I11300000040,I11300000361,Y,265.0,0.0,Y,NaN,93.0,23.0,...,NaN,153.3,0.0,Y,3.5,2.0,Y,6.15,4.0,8.0
1,001,I11300000117,NaN,N,NaN,NaN,N,NaN,NaN,23.0,...,NaN,141.0,0.0,N,NaN,NaN,N,NaN,NaN,0.0
2,001,I11300000138,I11300000534,Y,110.0,1.0,N,NaN,NaN,23.0,...,NaN,159.0,0.0,N,NaN,NaN,Y,0.63,0.0,1.0
3,001,I11300000143,I11300000358,Y,240.0,0.0,Y,NaN,95.0,23.0,...,NaN,129.3,0.0,N,NaN,NaN,Y,1.14,0.0,0.0
4,001,I11300000144,I11300000340,Y,347.0,0.0,Y,NaN,98.0,23.0,...,NaN,182.0,0.0,Y,0.6,0.0,Y,2.73,2.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7975,001,I11400060639,NaN,N,NaN,NaN,Y,NaN,99.0,23.0,...,NaN,157.0,0.0,N,NaN,NaN,N,NaN,NaN,0.0
7976,001,I11400060640,NaN,N,NaN,NaN,Y,NaN,95.0,23.0,...,NaN,147.3,0.0,N,NaN,NaN,N,NaN,NaN,0.0
7977,001,I11400060651,NaN,Y,119.0,1.0,Y,NaN,98.0,23.0,...,NaN,153.7,0.0,N,NaN,NaN,Y,2.32,2.0,4.0
7978,001,I11400060668,NaN,Y,188.0,0.0,Y,NaN,96.0,23.0,...,NaN,151.7,0.0,Y,0.9,0.0,Y,1.08,0.0,0.0
7979,001,I11400060679,NaN,N,NaN,NaN,Y,NaN,100.0,23.0,...,NaN,161.7,0.0,N,NaN,NaN,N,NaN,NaN,0.0

In [5]:
len(table5),len(table5['ACCOUNTNO'].unique())

(7979, 7979)

In [6]:
# CHECKITEM28B: FiO2只有1個是95，其他23, SOFASCORE為6個Score總分，CHECKITEM29也是GCS(用table2的)

table5_clear = table5[['ACCOUNTNO','CHECKITEM28A', 'CHECKITEM27', 'CHECKITEM27SCORE', 'CHECKITEM28SCORE',
                       'CHECKITEM29SCORE','CHECKITEM30SCORE','CHECKITEM31SCORE','CHECKITEM32SCORE']]

In [7]:
table5_clear

,ACCOUNTNO,CHECKITEM28A,CHECKITEM27,CHECKITEM27SCORE,CHECKITEM28SCORE,CHECKITEM29SCORE,CHECKITEM30SCORE,CHECKITEM31SCORE,CHECKITEM32SCORE
0,I11300000040,93.0,265.0,0.0,0.0,2.0,0.0,2.0,4.0
1,I11300000117,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2,I11300000138,NaN,110.0,1.0,NaN,0.0,0.0,NaN,0.0
3,I11300000143,95.0,240.0,0.0,0.0,0.0,0.0,NaN,0.0
4,I11300000144,98.0,347.0,0.0,0.0,3.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...
7975,I11400060639,99.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN
7976,I11400060640,95.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN
7977,I11400060651,98.0,119.0,1.0,0.0,1.0,0.0,NaN,2.0
7978,I11400060668,96.0,188.0,0.0,0.0,0.0,0.0,0.0,0.0
7979,I11400060679,100.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN

In [8]:
table5_clear.to_csv('table5_clear.csv', index=False)